In [ ]:
#for classifcation problem breast_cancer
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt
from sklearn.datasets import load_breast_cancer

In [ ]:
df = load_breast_cancer()

In [ ]:
dataset = pd.DataFrame(df.data)

In [ ]:
df

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [ ]:
dataset.columns = df.feature_names

In [ ]:
dataset.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [ ]:
# Dependent and independent varialbles
X = dataset
y = df.target

In [ ]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [ ]:
#train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=40)

In [ ]:
X_train

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
47         13.17         18.66           85.98      534.6          0.11580   
483        13.70         17.64           87.76      571.1          0.09950   
269        10.71         20.39           69.50      344.9          0.10820   
243        13.75         23.77           88.54      590.0          0.08043   
221        13.56         13.90           88.59      561.3          0.10510   
..           ...           ...             ...        ...              ...   
440        10.97         17.20           71.73      371.5          0.08915   
165        14.97         19.76           95.50      690.2          0.08421   
7          13.71         20.83           90.20      577.9          0.11890   
219        19.53         32.47          128.00     1223.0          0.08420   
326        14.11         12.88           90.03      616.5          0.09309   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
47            0.12310         0.12260              0.07340         0.2128   
483           0.07957         0.04548              0.03160         0.1732   
269           0.12890         0.08448              0.02867         0.1668   
243           0.06807         0.04697              0.02344         0.1773   
221           0.11920         0.07860              0.04451         0.1962   
..                ...             ...                  ...            ...   
440           0.11130         0.09457              0.03613         0.1489   
165           0.05352         0.01947              0.01939         0.1515   
7             0.16450         0.09366              0.05985         0.2196   
219           0.11300         0.11450              0.06637         0.1428   
326           0.05306         0.01765              0.02733         0.1373   

     mean fractal dimension  ...  worst radius  worst texture  \
47                  0.06777  ...         15.67          27.95   
483                 0.06088  ...         14.96          23.53   
269                 0.06862  ...         11.69          25.21   
243                 0.05429  ...         15.01          26.34   
221                 0.06303  ...         14.98          17.13   
..                      ...  ...           ...            ...   
440                 0.06640  ...         12.36          26.87   
165                 0.05266  ...         15.98          25.82   
7                   0.07451  ...         17.06          28.14   
219                 0.05313  ...         27.90          45.41   
326                 0.05700  ...         15.53          18.00   

     worst perimeter  worst area  worst smoothness  worst compactness  \
47            102.80       759.4           0.17860            0.41660   
483            95.78       686.5           0.11990            0.13460   
269            76.51       410.4           0.13350            0.25500   
243            98.00       706.0           0.09368            0.14420   
221           101.10       686.6           0.13760            0.26980   
..               ...         ...               ...                ...   
440            90.14       476.4           0.13910            0.40820   
165           102.30       782.1           0.10450            0.09995   
7             110.60       897.0           0.16540            0.36820   
219           180.20      2477.0           0.14080            0.40970   
326            98.40       749.9           0.12810            0.11090   

     worst concavity  worst concave points  worst symmetry  \
47           0.50060               0.20880          0.3900   
483          0.17420               0.09077          0.2518   
269          0.25340               0.08600          0.2605   
243          0.13590               0.06106          0.2663   
221          0.25770               0.09090          0.3065   
..               ...                   ...             ...   
440          0.47790               0.15550         

In [ ]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0,

In [ ]:
lr = LogisticRegression()

In [ ]:
X_test

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
295        13.77         13.27           88.06      582.7          0.09198   
16         14.68         20.13           94.74      684.5          0.09867   
431        12.40         17.68           81.47      467.8          0.10540   
453        14.53         13.98           93.86      644.2          0.10990   
15         14.54         27.54           96.73      658.8          0.11390   
..           ...           ...             ...        ...              ...   
519        12.75         16.70           82.51      493.8          0.11250   
386        12.21         14.09           78.78      462.0          0.08108   
494        13.16         20.54           84.06      538.7          0.07335   
172        15.46         11.89          102.50      736.9          0.12570   
377        13.46         28.21           85.89      562.1          0.07517   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
295           0.06221         0.01063              0.01917         0.1592   
16            0.07200         0.07395              0.05259         0.1586   
431           0.13160         0.07741              0.02799         0.1811   
453           0.09242         0.06895              0.06495         0.1650   
15            0.15950         0.16390              0.07364         0.2303   
..                ...             ...                  ...            ...   
519           0.11170         0.03880              0.02995         0.2120   
386           0.07823         0.06839              0.02534         0.1646   
494           0.05275         0.01800              0.01256         0.1713   
172           0.15550         0.20320              0.10970         0.1966   
377           0.04726         0.01271              0.01117         0.1421   

     mean fractal dimension  ...  worst radius  worst texture  \
295                 0.05912  ...         14.67          16.93   
16                  0.05922  ...         19.07          30.88   
431                 0.07102  ...         12.88          22.91   
453                 0.06121  ...         15.80          16.93   
15                  0.07077  ...         17.46          37.13   
..                      ...  ...           ...            ...   
519                 0.06623  ...         14.45          21.74   
386                 0.06154  ...         13.13          19.29   
494                 0.05888  ...         14.50          28.46   
172                 0.07069  ...         18.79          17.04   
377                 0.05763  ...         14.69          35.63   

     worst perimeter  worst area  worst smoothness  worst compactness  \
295            94.17       661.1            0.1170             0.1072   
16            123.40      1138.0            0.1464             0.1871   
431            89.61       515.8            0.1450             0.2629   
453           103.10       749.9            0.1347             0.1478   
15            124.10       943.2            0.1678             0.6577   
..               ...         ...               ...                ...   
519            93.63       624.1            0.1475             0.1979   
386            87.65       529.9            0.1026             0.2431   
494            95.29       648.3            0.1118             0.1646   
172           125.00      1102.0            0.1531             0.3583   
377            97.11       680.6            0.1108             0.1457   

     worst concavity  worst concave points  worst symmetry  \
295          0.03732               0.05802          0.2823   
16           0.29140               0.16090          0.3029   
431          0.24030               0.07370          0.2556   
453          0.13730               0.10690          0.2606   
15           0.70260               0.17120          0.4218   
..               ...                   ...             ...   
519          0.14230               0.08045         

In [ ]:
lr.fit(X_train, y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
lr.predict(X_test)

array([1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1])